cc_test(
  name = "EverythingTest",
  size = "small",
  srcs = glob(
    ["**/*.cc"]
  ),
  deps = [
    "@com_google_googletest//:gtest_main", 
    "//LibMath:LibMath",
    "//LibString:LibString",
    ],
)
